it was getting upgraded to https
and thus fails hmm.

 Content Security Policy: Upgrading insecure request ‘http://0.0.0.0/’
 to use ‘https’

 TypeError: NetworkError when attempting to fetch resource.